FORMAT: 1A
HOST: http://www.test.com

# fake settlement data
nothig to see here.


## SettlementData Collection [/settlementdata]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "currency": "GBP", "member": "douglas", "settledAmount": 123, "outstandingAmount": 546, "payableOrRecievable": "payable", "comments": ""
        }, {
          "id": 2, "currency": "GBP", "member": "douglas", "settledAmount": 555, "outstandingAmount": 888, "payableOrRecievable": "payable", "comments": "test"
        }]

### Create some settlement data [POST]
+ Request (application/json)

        { "currency": "GBP", "member": "douglas", "settledAmount": 123, "outstandingAmount": 546, "payableOrRecievable": "payable", "comments": "" }

+ Response 201 (application/json)

        { "id": 1, "currency": "GBP", "member": "douglas", "settledAmount": 123, "outstandingAmount": 546, "payableOrRecievable": "payable", "comments": "" }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office 7" }

### Remove a Note [DELETE]
+ Response 204
