FORMAT: 1A
HOST: http://www.test.com

# fake settlement data
nothig to see here.


## SettlementData Collection [/settlementdata]
### List all SettlementData [GET]
+ Response 200 (application/json)
{
"todaysSettlementData": 
        [{
          "id": 1, "currency": "GBP", "member": "douglas", "settledAmount": 123, "outstandingAmount": 546, "payableOrRecievable": "payable", "comments": ""
        }, {
          "id": 2, "currency": "GBP", "member": "douglas", "settledAmount": 555, "outstandingAmount": 888, "payableOrRecievable": "payable", "comments": "test"
        }]
}

### Create some settlement data [POST]
+ Request (application/json)

        { "currency": "GBP", "member": "douglas", "settledAmount": 123, "outstandingAmount": 546, "payableOrRecievable": "payable", "comments": "" }

+ Response 201 (application/json)

        [{
          "id": 1, "currency": "GBP", "member": "douglas", "settledAmount": 123, "outstandingAmount": 546, "payableOrRecievable": "payable", "comments": ""
        },{
          "id": 1, "currency": "GBP", "member": "douglas", "settledAmount": 123, "outstandingAmount": 546, "payableOrRecievable": "payable", "comments": ""
        }, {
          "id": 2, "currency": "GBP", "member": "douglas", "settledAmount": 555, "outstandingAmount": 888, "payableOrRecievable": "payable", "comments": "test"
        }]

## SettlementData [/settlementdata/{id}]
A single SettlementData object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the SettlementData to perform action with. Has example value.

### Retrieve a SettlementData [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

             { "id": 1, "currency": "GBP", "member": "douglas", "settledAmount": 123, "outstandingAmount": 546, "payableOrRecievable": "payable", "comments": "" }

### Remove a SettlementData [DELETE]
+ Response 204
